version: "3"

services:
  db:
    container_name: covidrome-postgres
    build:
      context: ./docker/postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
    environment:
      # master password
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=test
      # Covidrome user
      - POSTGRES_COVIDROME_USER=covidrome
      - POSTGRES_COVIDROME_PASSWORD=test
    ports:
      - "5435:5432"
    volumes:
      - covidrome-pgdata:/var/lib/postgresql/data

volumes:
  covidrome-pgdata:
